# Generated by Django 5.2.17 on 2026-08-17 10:26

import apps.listings.models.listing
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('category', models.CharField(choices=[('property', 'Property'), ('vehicles', 'Vehicles'), ('jobs', 'Jobs'), ('services', 'Services'), ('marketplace', 'Marketplace'), ('business', 'Business'), ('nearby', 'Nearby')], max_length=20)),
                ('subcategory', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=40)),
                ('negotiable', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=15)),
                ('contact_via', models.CharField(choices=[('phone', 'Phone'), ('chat', 'Chat'), ('whatsapp', 'WhatsApp'), ('both', 'Phone and chat')], default='phone', max_length=12)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('promote_requested', models.BooleanField(default=False)),
                ('is_promoted', models.BooleanField(default=False)),
                ('admin_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=apps.listings.models.listing.listing_photo_path)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
