# Generated by Django 6.0.7 on 2026-08-23 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_reviews_and_engagement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='listingcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='listings.listingcomment'),
        ),
    ]
