# Generated by Django 6.0.7 on 2026-08-20 12:02

import apps.notifications.models.notice
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True, default='')),
                ('audience', models.CharField(choices=[('all', 'All users'), ('buyer', 'Buyers only'), ('provider', 'Sellers only')], default='all', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to=apps.notifications.models.notice.notice_image_path)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
