# Generated by Django 5.2.17 on 2026-08-20 15:10

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_branding_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingconfig',
            name='emergency_email',
            field=models.EmailField(blank=True, default='support@najik.com', max_length=254),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='emergency_phone',
            field=models.CharField(blank=True, default='01-5970123', max_length=40),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='website',
            field=models.CharField(blank=True, default='www.najik.com', max_length=120),
        ),
        migrations.AlterField(
            model_name='brandingconfig',
            name='authorized_signatory',
            field=models.ImageField(blank=True, upload_to=apps.core.models.signatory_path),
        ),
    ]
