# Generated by Django 6.0.7 on 2026-08-24 05:22

import apps.core.models.seller_wallet
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seller_wallet'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallettransaction',
            name='boost_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='promotions.boostcampaign'),
        ),
        migrations.AlterField(
            model_name='sellerloadrequest',
            name='proof_image',
            field=models.ImageField(blank=True, upload_to=apps.core.models.seller_wallet.load_proof_path),
        ),
        migrations.AlterField(
            model_name='sellerpaymentconfig',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=apps.core.models.seller_wallet.payment_qr_path),
        ),
        migrations.AlterField(
            model_name='sellerwallettransaction',
            name='kind',
            field=models.CharField(choices=[('load', 'Load approved'), ('listing_fee', 'Listing fee'), ('boost_fee', 'Boost promotion'), ('admin_credit', 'Admin credit'), ('admin_debit', 'Admin debit'), ('refund', 'Refund'), ('referral_reward', 'Refer & Earn reward')], max_length=16),
        ),
    ]
