# Generated by Django 6.0.7 on 2026-08-27 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_privacy_compliance(apps, schema_editor):
    PrivacyRetentionConfig = apps.get_model("core", "PrivacyRetentionConfig")
    PrivacyRetentionConfig.objects.get_or_create(pk=1)
    from apps.core.legal_defaults import ensure_legal_documents

    ensure_legal_documents()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_buyer_payment_config'),
        ('staff', '0004_staffloginlockout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyRetentionConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('inactive_account_retention_days', models.PositiveIntegerField(default=365, help_text='Days to keep deactivated accounts before automated purge (0 = never auto-purge).')),
                ('kyc_retention_days_after_deletion', models.PositiveIntegerField(default=730, help_text='How long KYC metadata may be retained after account deletion (policy display; files deleted with account).')),
                ('chat_message_retention_days', models.PositiveIntegerField(default=365, help_text='Delete chat messages older than this many days (0 = keep forever).')),
                ('login_lockout_retention_days', models.PositiveIntegerField(default=90)),
                ('staff_login_attempt_retention_days', models.PositiveIntegerField(default=180)),
                ('otp_retention_days', models.PositiveIntegerField(default=30)),
                ('password_reset_token_retention_days', models.PositiveIntegerField(default=7)),
                ('allow_self_service_export', models.BooleanField(default=True)),
                ('allow_self_service_delete', models.BooleanField(default=True)),
                ('require_password_for_self_delete', models.BooleanField(default=True)),
                ('anonymize_complaint_snapshots_on_delete', models.BooleanField(default=True)),
                ('retention_policy_summary', models.TextField(blank=True, default='We retain account data while your account is active. After deletion, some records may be kept for fraud prevention, legal compliance, and dispute resolution for the periods shown below.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'privacy & retention config',
                'verbose_name_plural': 'privacy & retention config',
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('export', 'Export'), ('delete', 'Delete'), ('retention_purge', 'Retention purge')], max_length=20)),
                ('source', models.CharField(choices=[('self', 'User self-service'), ('staff', 'Staff admin'), ('system', 'Automated retention job')], max_length=16)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_email', models.CharField(blank=True, default='', max_length=254)),
                ('user_phone', models.CharField(blank=True, default='', max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_subject_logs', to='staff.staffuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy')], db_index=True, max_length=16)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Service provider (seller)')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('last_updated_label', models.CharField(blank=True, default='', max_length=40)),
                ('intro', models.TextField(blank=True, default='')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('footer', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['doc_type', 'role'],
                'unique_together': {('doc_type', 'role')},
            },
        ),
        migrations.RunPython(seed_privacy_compliance, migrations.RunPython.noop),
    ]
