# Generated by Django 6.0.7 on 2026-08-17 06:54

import apps.verification.models.application
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(max_length=40)),
                ('nagrita', models.FileField(upload_to=apps.verification.models.application.nagrita_path)),
                ('photo', models.FileField(upload_to=apps.verification.models.application.photo_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
