# Generated by Django 5.2.17 on 2026-08-20 10:35

import apps.verification.models.application
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_providerapplication_pending_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='nation_card',
            field=models.FileField(blank=True, upload_to=apps.verification.models.application.nation_card_path),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='other_document',
            field=models.FileField(blank=True, upload_to=apps.verification.models.application.other_document_path),
        ),
    ]
