# Generated by Django 5.2.17 on 2026-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_providerapplication_nation_card_other_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='rejection_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
