# Generated by Django 5.2.17 on 2026-08-20 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('verification', '0005_providerapplication_profile_data_rejection_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderIdCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('verify_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('access_status', models.CharField(choices=[('blocked', 'Blocked'), ('requested', 'Download requested'), ('approved', 'Download approved')], default='blocked', max_length=16)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('staff_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_id_cards', to='staff.staffuser')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
