# Generated by Django 6.0.7 on 2026-08-24 05:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0010_comment_replies'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostPricing',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('boost_3d_rupees', models.PositiveIntegerField(default=50)),
                ('boost_7d_rupees', models.PositiveIntegerField(default=100)),
                ('boost_14d_rupees', models.PositiveIntegerField(default=180)),
                ('boost_30d_rupees', models.PositiveIntegerField(default=300)),
                ('max_active_boosts_per_seller', models.PositiveIntegerField(default=3)),
                ('max_active_boosts_per_category', models.PositiveIntegerField(default=20)),
                ('max_active_boosts_platform', models.PositiveIntegerField(default=100)),
                ('rotation_interval_minutes', models.PositiveIntegerField(default=30)),
                ('max_slots_per_category_feed', models.PositiveIntegerField(default=5)),
                ('seller_view_multiplier', models.PositiveIntegerField(default=5)),
                ('est_views_per_day_3d', models.PositiveIntegerField(default=50)),
                ('est_views_per_day_7d', models.PositiveIntegerField(default=45)),
                ('est_views_per_day_14d', models.PositiveIntegerField(default=40)),
                ('est_views_per_day_30d', models.PositiveIntegerField(default=35)),
                ('est_inquiries_per_100_views', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'boost pricing',
                'verbose_name_plural': 'boost pricing',
            },
        ),
        migrations.CreateModel(
            name='BoostCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('duration_days', models.PositiveIntegerField()),
                ('price_paid_paisa', models.PositiveBigIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('category', models.CharField(max_length=20)),
                ('current_slot', models.PositiveSmallIntegerField(default=0)),
                ('last_rotation_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_rotations', models.PositiveIntegerField(default=0)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('last_impression_at', models.DateTimeField(blank=True, null=True)),
                ('admin_paused_reason', models.TextField(blank=True, default='')),
                ('admin_extended_hours', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_campaigns', to='listings.listing')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_reviews', to='staff.staffuser')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category', 'ends_at'], name='promotions__status_7eabea_idx'), models.Index(fields=['listing', 'status'], name='promotions__listing_44dee2_idx'), models.Index(fields=['seller', 'status'], name='promotions__seller__b0a7d3_idx')],
            },
        ),
    ]
