# Generated by Django 6.0.7 on 2026-08-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_boostcampaigninquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boostpricing',
            name='seller_view_multiplier',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
