# Generated by Django 5.2.17 on 2026-08-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='staff_warning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appuser',
            name='staff_warning_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
