# Generated by Django 6.0.7 on 2026-08-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_referral_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referearnconfig',
            name='description',
            field=models.TextField(blank=True, default='Each invite code works for one friend only. Share your code — when they register as a verified seller and publish their first live listing, you get the reward in Payments. A new code is generated after each successful invite.'),
        ),
    ]
