# Generated by Django 5.2.17 on 2026-08-20 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('listings', '0004_listing_lat_lng'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('user', 'User report'), ('listing', 'Listing report'), ('chat', 'Chat report')], max_length=16)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('reason', models.TextField()),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('listing_snapshot', models.JSONField(blank=True, default=dict)),
                ('reporter_snapshot', models.JSONField(blank=True, default=dict)),
                ('accused_snapshot', models.JSONField(blank=True, default=dict)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('warning_sent_to', models.CharField(blank=True, default='', max_length=20)),
                ('warning_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('accused', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_against', to=settings.AUTH_USER_MODEL)),
                ('chat_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='chat.chatreport')),
                ('chat_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='chat.chatthread')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='listings.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
