# Generated by Django 5.2.17 on 2026-08-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice'), ('location', 'Location'), ('booking', 'Booking')], default='text', max_length=12),
        ),
    ]
